cloudflare/wrangler-action

README.md

Preparing for large Github Action operations where many secrets are stored, and naming gets confusing.
`CLOUDFLARE_API_KEY`	
`CLOUDFLARE_EMAIL`

changed secrets naming

---

README.md
action.yml
entrypoint.sh

This addresses https://github.com/cloudflare/wrangler-action/issues/3
Usage is as suggested in the issue:
```
- name: Publish worker one
uses: cloudflare/wrangler-action@1.0.0
with:
apiKey: ${{ secrets.CF_API_KEY }}
email: ${{ secrets.CF_EMAIL }}
workingDirectory: 'worker-one'
- name: Publish worker two
uses: cloudflare/wrangler-action@1.0.0
with:
apiKey: ${{ secrets.CF_API_KEY }}
email: ${{ secrets.CF_EMAIL }}
workingDirectory: 'worker-two'
```

Add workingDirectory option for publishing a subdirectory

---

.github/workflows/deploy.yml
README.md
action.yml
entrypoint.sh
test/workers-site/index.js

Proposed solution for publishing worker secrets #19.
Worker secrets can be optionally passed as a new line deliminated string of names in `secrets`.  Each secret name must match an environment variable name specified in the `env` attribute.  Creates or replaces the value for the Worker secret using the `wrangler secret put` command.
```yaml
jobs:
deploy:
steps:
uses: cloudflare/wrangler-action@1.1.0
with:
apiToken: ${{ secrets.CF_API_TOKEN }}
workingDirectory: 'subfoldername'
secrets: |
SECRET1
SECRET2
env:
SECRET1: ${{ secrets.SECRET1 }}
SECRET2: ${{ secrets.SECRET2 }}
```
Blends the usage of both an input field and the env attribute as a means for configuring the Action to perform `wrangler secret put` commands on provided key values.  
The env attribute is well suited for specifying …

add secrets publishing

---

README.md

The readme mentions v1.2.0 but some of the commands (for example publish)
are only present in v1.3.0. Update readme to use v1.3.0 instead.
Thanks!

Update Readme to reference v1.3.0

---

README.md

Addresses https://github.com/cloudflare/wrangler-action/issues/40
Seems like most of the people in forums who were asking for `workflow_dispatch` were interested in the UI, so I opted out of updating the CLI example.  The docs in the link seem high enough quality that it doesn't need repeating here.

Suggest workflow_dispatch for manual deploys

---

README.md

This change updates the release version for cloudflare/wrangler-action in all examples from `1.2.0` to `1.3.0`.
It also corrects a typo on the last example changing `TOML` to `YAML` based on the code below it.

Update README.md release version

---

CHANGELOG.md
Dockerfile
README.md
action.yml
entrypoint.sh

Whooo! Wrangler 2 is awesome :)
Since this is v2 I did make 2 breaking changes but the migration path is super simple.
* Remove `publish: true` with `command: publish`.
---
You can see it working for a Worker publish here: https://github.com/WalshyDev/wrangler-action-test/runs/6310845616?check_suite_focus=true
You can see it working for a Pages deployment here: https://github.com/WalshyDev/wrangler-action-test/runs/6327883564?check_suite_focus=true
cc: @GregBrimble @eidam @Ekwuno

Support wrangler2 - v2

---

.changeset/itchy-buses-grow.md
src/index.ts

Previously, we prevented any error logs from propagating too far to prevent leaking of any potentially sensitive information. However, this made it difficult for developers to debug their code.
In this release, we have updated our error handling to allow for more error messaging from pre/post and custom commands. We still discourage the use of these commands for secrets or other sensitive information, but we believe this change will make it easier for developers to debug their code.
Example of output in `act` local run:
```ts
[...wrangler_action_self_testing]   ❓  ::group::🚀 Executing Wrangler Commands
[...wrangler_action_self_testing]   ❗  ::error::✘ [ERROR] Unknown arguments: dry-run, dryRun, asdf, deploy%0A%0A%0A
[...wrangler_action_self_testing]   ❓  ::endgroup::
```
Relates to #137

Additional Error Handling

---

.changeset/gold-moose-check.md
.github/workflows/deploy.yml
.github/workflows/workerHealthCheck.cjs
action-env-setup.ts
action.yml
package-lock.json
package.json
src/index.ts
vitest.config.ts

Some of the stderr, stdout, info & groupings can be a little noisy for some users and use cases. This feature allows for a option to be passed 'quiet: true' this would significantly reduce the noise.
There will still be output that lets the user know Wrangler Installed and Wrangler Action completed successfully. Any failure status will still be output to the user as well, to prevent silent failures.
resolves #142

Quiet feature

---

.github/workflows/release.yml

Followup to #159.
We [forgot](https://github.com/cloudflare/wrangler-action/actions/runs/6026367403/job/16349123621) to manually provide the `tag_name` input to the `JasonEtco/build-and-tag-action@v2` action. It previously got the tag name from the `release` event payload, but we're no longer running its workflow on that event.

add `tag_name` input to Tag & Release Action step of release workflow

---

.github/workflows/release.yml

Another followup to #159. We forgot to move the build step over.

Build action before pushing dist-tags

---

action.yml

Action runner [v2.308.0](https://github.com/actions/runner/releases/tag/v2.308.0) added `node20` support. Since everything else (`@types/node`, `node-version` in workflows, etc) in this project is reference `latest` (current `20.x`), I figured the tool itself should also be on `20.x`.
Also for future reference, all possible node values for `using` is in [NodeUtil.cs](https://github.com/actions/runner/blob/main/src/Runner.Common/Util/NodeUtil.cs#L9). I also put it in as a comment in the `action.yml` for easier future reference, but feel free to remove if it feels out of place.

Update action to use Node 20

---

.changeset/slimy-cameras-play.md
.github/workflows/deploy.yml
action.yml
src/index.ts
src/packageManagers.test.ts
src/packageManagers.ts
src/utils.test.ts
src/utils.ts

Fixes #180
#173 added a new `packageManager` input to allow users to *optionally* specify which package manager they'd like to use when running the action. If the value isn't specified, it attempts to infer the appropriate package manager based on the presence of a lockfile. However, if no lockfile is found it throws an error. This was an inadvertent breaking change.
Instead of throwing an error when the input isn't specified and no lockfile is found, we should now fallback to the previous behavior of using npm. Specifying an unsupported package manager, however, throws an error.
This PR also refactors the package manager logic and tests into its own module.

Use npm as fallback if no `packageManager` specified

---

.changeset/forty-poets-guess.md
action.yml
src/packageManagers.test.ts
src/packageManagers.ts
test/bun/index.ts
test/bun/package.json
test/bun/wrangler.toml

This PR adds [Bun](https://bun.sh/) support and closes #187.
I wrote the PR before I read the contributing guidelines (sorry) and did not make an issue before I started working. As such, if you decline this it's not a big deal.
However, worth noting, it does work and I can deploy my website to CF pages with this.

Add bun support

---

.changeset/dirty-poets-swim.md
action.yml
src/packageManagers.test.ts
src/packageManagers.ts
test/bun/package.json

In #190 I set `default: npm` in [action.yml](https://github.com/cloudflare/wrangler-action/pull/190/files#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R47), not realizing this sets the actual input value when it's not provided explicitly (as opposed to just serving as documentation) 🤦🏻‍♂️. This prevented [lockfile inference](https://github.com/cloudflare/wrangler-action/pull/190/files#diff-06a2cb031ff1828e1a5a18c28165d5337828e0fba051b5a4c9569056009c096aR59) from ever happening, since the `packageManager` value would never be empty.
This PR removes the default value, allowing the lockfile inference to happen before ultimately falling back to `"npm"`.

Don't set `packageManager` default via action.yml

---

test/base/package.json
test/bun/package.json
test/empty/package.json
test/environment/package.json
test/pnpm/package.json
test/yarn/package.json

This is mostly to prevent yarn from raising a [warning](https://github.com/cloudflare/wrangler-action/actions/runs/6483917006/job/17606557543#step:20:28) during our test runs.

Add missing licenses to dummy test packages

---

.changeset/proud-insects-add.md
.changeset/warm-mugs-judge.md
package-lock.json
package.json
src/exec.ts
src/index.ts

Instead of using a mix of `child_process.exec`, `child_process.execSync` and a promisified version of `child_process.exec`, we now (mostly) just use [`@actions/exec`](https://github.com/actions/toolkit/blob/main/packages/exec/README.md). That runs `child_process.spawn` under the hood and handles a lot of character escaping for us. We can also now pass Buffers directly into the subprocess as stdin instead of relying on shell piping.
This ends up fixing a few problems we had where secrets and env var values containing shell metacharacters were being misinterpreted.
Unfortunately, `@actions/exec` doesn't support running with a shell. That means we still have to roll our own wrapper around `child_process.exec` to avoid a breaking change to `preCommands` and `postCommands`, since users might …

Refactor subprocess execution to use `@actions/exec`

---

README.md

If the token isn't specified, wrangler throws this error, indicating the CLOUDFLARE_API_TOKEN should be set, so it's worth being consistent so folks can copy/paste the examples and have it work out of the box:
```
In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work.
```

Swap CF_API_TOKEN with CLOUDFLARE_API_TOKEN

---

.github/workflows/release.yml

Currently our release process is kicked off whenever a PR is merged and there are no changesets within the `.changeset` directory. Typically this happens when we intend to publish a release, just after we merge a "Version Packages" PR which removes the changesets and adds the entries to our changelog.
However, this also means that merging any PR without user-facing changes during the period after we've made a release will trigger another release (which luckily fails because the created tag already exists on the remote. See #184).
This change avoids that scenario by fetching tags when checking out the repo. Now when `npx changeset tag` runs, it will see that the tag already exists and skip creating it (`🦋  Skipping tag (already exists):  v3.3.2`). The `git push --tags` step will no longer …

Don't attempt to publish when there's no pending release

---

.changeset/weak-lobsters-march.md
package-lock.json
package.json
src/utils.test.ts
src/utils.ts

fixes #215 
closes #214 
This also bumps a few dependencies, to remove some `npm audit` warnings. The output bundle increases from `964kB` to `983kB`, but I feel the 19kB increase is worth the reliable semver comparison.

fix: semver comparison

---

.changeset/sixty-moons-switch.md
package-lock.json
src/index.ts

(enhancement): Surface inner exception when secret:bulk upload command fails

---

README.md

`actions/checkout@v3` runs on node16 which is sunset by GitHub Action runners.
resolves https://github.com/cloudflare/wrangler-action/issues/232

Update README.md to remove deprecation warnings

---

README.md

just something I bumped into today

docs: add warning about packageManager config

---

README.md

This effectively reverts https://github.com/cloudflare/wrangler-action/pull/242.
---
This is inferred by https://github.com/cloudflare/wrangler-action/pull/190 and then fixed in https://github.com/cloudflare/wrangler-action/pull/193, and I'm not really sure the "default" copy/pasted config should use `pnpm` - that's definitely not the standard.
> The package manager you'd like to use to install and run wrangler. If not specified, the preferred package manager will be inferred based on the presence of a lockfile or fallback to using npm if no lockfile is found. Valid values are npm | pnpm | yarn | bun.
You do not need to specify `packageManager` as the docs now suggests, as long as you're running an up to date version.
If there is a bug in the package manager detection, I'd suggest that …

docs: remove warning about packageManager and pnpm default

---

README.md

This PR adds instructions to README for how to upload a Worker Version using this Github Action.
There are no code changes so a changeset is not required.

Add `versions upload` instructions to README

---

.changeset/funny-boats-care.md
src/index.ts

testiing #255

---

.changeset/little-cougars-shout.md
README.md
action.yml
src/index.ts

Since the lovely PR https://github.com/cloudflare/workers-sdk/pull/6643 that landed in Wrangler 3.78.0 it's now possible to get the deployment alias from the `pages deploy` output too.
This PR exposes that in a backwards compatible way. When there is no alias (or on older Wrangler versions) it'll just not be set.
I tested this in our local repo on commit https://github.com/Ambroos/wrangler-action/commit/6dcec6789d82c53bb800db578877e56cc81c2c45 (which contains dist) but is otherwise identical to this PR, and things seem very functional. Output below:
```
Run Ambroos/wrangler-action@6dcec6789d82c53bb800db578877e56cc8[1](snip#step:13:1)c2c45
with:
wranglerVersion: 3.78.5
apiToken: ***
accountId: ***
workingDirectory: packages/snip
command: pages deploy "snip" --project-name=snip …
```

Add deployment-alias-url for pages deployments with Wrangler 3.78.0+

---

src/index.ts

Hi folks, several users using this action have reported observability enabled=true not working in there wrangler configs
Tracked the issue down to the default version here being out of date.
I would be grateful if we could bump this up to the latest

WO-202: update wrangler version so the github action works out of the box with Workers Observability

---

.changeset/gentle-cobras-move.md
src/index.ts

implements #277
i don’t know how to test or verify this, but in case it’s helpful, here’s my proposed solution (assuming my hypothesis from #277 is correct).
i think this will also fix the issue documented here: https://github.com/cloudflare/wrangler-action/issues/199#issuecomment-2188863592

When checking for existing wrangler install, match wrangler version even if multiline output

---

.changeset/fast-experts-shop.md
package-lock.json
package.json
src/index.ts
src/wranglerArtifactManager.test.ts
src/wranglerArtifactManager.ts

Enables Pages deploys to provide outputs for id, environment, url, and alias, just like they can in pages-action. The current way of getting deploy outputs with Workers is via wrangler output to std out, but this information for Pages was not available in std out.
Because of that, this change adds a new method for getting outputs via wrangler artifacts.
The new outputs look like this in the Actions view.
When an alias is not available in the artifact:
When an alias is available in the artifact:
When we don't get stuff back from the request for artifact:

Add parity with pages-action for Pages deploy outputs

---

.changeset/brave-wasps-greet.md
README.md
action.yml
package-lock.json
package.json
src/index.ts
src/wranglerArtifactManager.test.ts
src/wranglerArtifactManager.ts

Unreverts #303 
Tested pipelines here:
- [Pipeline](https://github.com/Maximo-Guk/demo-actions/actions/runs/11607252464/job/32320464024#step:5:9) shows all outputs if wrangler version >=3.81.0
- [Pipeline](https://github.com/Maximo-Guk/demo-actions/actions/runs/11607284817/job/32320541183#step:5:9) falls back to only outputting `deployment-url` and `deployment-alias-url` if wrangler version doesn't output metadata file
Moves wrangler output to tmpdir rather than /opt/ since /opt/ is owned by root.
- Github self hosted runners may not have permissions to write to /opt/ #306 
- Also fallsback to trying to extract the deployment-url and deployment-alias-url from stdout when WRANGLER_OUTPUT_DIR is not specified

Unrevert add parity with wrangler action

---

src/index.ts

Addresses #317,
Problem: If a user runs wrangler-action multiple times we'll return the wrong `deployment-url`, as we only return the first detailed deployment instance from the artifact file.
Solution: Let's generate a new output directory with a randomUUID in the tmpDir, so that when the action is ran multiple times, we use the artifacts from that run, opposed to the artifacts from a previous run.
Tested here: 
[Returns correct output for first run](https://github.com/Maximo-Guk/demo-actions/actions/runs/11692341714/job/32561485822#step:5:9)
[Returns correct output for second run ](https://github.com/Maximo-Guk/demo-actions/actions/runs/11692341714/job/32561485822#step:7:10)

Use random UUID when creating wrangler artifacts output directory

---

.changeset/tiny-pillows-return.md
src/service/github.ts
src/wranglerArtifactManager.ts

See #344.
Just opening a new PR so that I could add a changeset and remove stages field from the zod schema. This field was never added in the original wrangler PR. https://github.com/cloudflare/workers-sdk/pull/7252

fix: pages github deployment not triggering due to incorrect condition #2

---

src/service/github.ts

After a few tries on different repos, and after a migration from `cloudflare/pages-action` to `cloudflare/wrangler-action`, the feature to add Github deployment and summary is not working.
```bash
CLOUDFLARE_API_TOKEN=xxx WRANGLER_OUTPUT_FILE_DIRECTORY=tmp CI=true \
npx wrangler pages deploy ./dist --project-name=my-project --branch=test/branch-deployment
cat tmp/wrangler-output-xxx.json | jq 'select(.type == "pages-deploy-detailed") | .stages'
```
Remove the conditional for `stages` as it's optional, not used in the action and currently preventing the Summary/Deployment to be generated.

fix: pages github deployment not triggering due to incorrect condition

---

.changeset/lemon-bags-happen.md
src/service/github.ts
src/utils.ts

Addresses #347. 
We shouldn't hard fail the action if we have issues creating the Github deployment and Github job summary.

Handle failures in createGitHubDeployment and createGitHubJobSummary
